Sbl3
projectceladon/device-intel-build pull request #158
Opened 2023-07-31 14:29 UTC by GangSecurity

2023-08-01 05:56 UTC, dyang23 approved these changes
LGTM

2023-08-01 07:33 UTC, swaroopbalan approved these changes

2023-08-01 09:31 UTC, JeevakaPrabu requested changes
Can we change the commit message to ?
Add iso_image option to enable/disable building of iso images

make flashfiles takes long time.

In order to reduce image generation time provided option to skip
building of ISO image. If user wants to skip building of ISO image
make command to use is "make flashfiles iso_image=false"

Tracked-On: OAM-111036
Signed-off-by: Chen, Gang G <gang.g.chen@intel.com>

2023-08-01 10:23 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/393

Done by "Chen, Gang G" <gang.g.chen@intel.com>

2023-08-01 10:23 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/261

2023-08-02 07:34 UTC, JeevakaPrabu approved these changes

2023-08-02 07:52 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: ComputeDependencies The list of changes is different than the one in the preintegration.
Errors:
  ('github', 'projectceladon/device-intel-build', 158) preintegration patchset:1f11cec..a99a502, currentpatchset:1f11cec..9730336

More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/264

2023-08-02 10:01 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/396

Done by "Chen, Gang G" <gang.g.chen@intel.com>

2023-08-02 10:31 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/265

Done by "Chen, Gang G" <gang.g.chen@intel.com>

2023-08-02 15:12 UTC, merged

2023-08-02 15:13 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Chen, Gang G" <gang.g.chen@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/231